
Traceback (most recent call last):
  File "/home/creditizens/djangochatAI/chatbotAI/log_analysis_center/log_analyzer_graph.py", line 7, in <module>
    from logs_advice_report_creation import CONNECTION_STRING, get_advice_on_logs
  File "/home/creditizens/djangochatAI/chatbotAI/log_analysis_center/logs_advice_report_creation.py", line 8, in <module>
    import call_llm, prompt_creation
  File "/home/creditizens/djangochatAI/chatbotAI/log_analysis_center/call_llm.py", line 22, in <module>
    from llms import (
  File "/home/creditizens/djangochatAI/chatbotAI/log_analysis_center/llms.py", line 12, in <module>
    temperature=float(os.getenv("GROQ_TEMPERATURE")),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'NoneType'
Traceback (most recent call last):
  File "/home/creditizens/djangochatAI/chatbotAI/log_analysis_center/log_analyzer_graph.py", line 7, in <module>
    from logs_advice_report_creation import CONNECTION_STRING, get_advice_on_logs
  File "/home/creditizens/djangochatAI/chatbotAI/log_analysis_center/logs_advice_report_creation.py", line 8, in <module>
    import call_llm, prompt_creation
  File "/home/creditizens/djangochatAI/chatbotAI/log_analysis_center/call_llm.py", line 22, in <module>
    from llms import (
  File "/home/creditizens/djangochatAI/chatbotAI/log_analysis_center/llms.py", line 12, in <module>
    temperature=float(os.getenv("GROQ_TEMPERATURE")),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'NoneType'
/bin/sh: 1: /home/creditizens/djangochatAI/chatbotAI/venv/bin/python: not found
